### ISSUE TITLE
[BUG]Not able to send message from Notification Channel

### ISSUE THREAD

**Issue by vslekshminarasimhan** [opensearch-project/dashboards-notifications#129]
Not able to send test message and messages from Notificaiton Channel. Message is not getting triggered on alert condition. 
<img width="960" alt="opensearch notification channel" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/63218929/25bf600c-e949-4c21-a478-15c6c5574bfc">

**Comment by Hailong-am** [comment]
@vslekshminarasimhan can you share the full error?

**Comment by vslekshminarasimhan** [comment]
Classification: Confidential
Hi,

Step 1: I am creating an alert in opensearch.
***@***.***



Step 2: Create Monitor
***@***.***


Step 3: creating a monitor
***@***.***

***@***.***

***@***.***

***@***.***



Step 4:


***@***.***



Step 5: Add Action


***@***.***


Step 6 Clicking the Send Test Message getting the "Failed to send the message" popup with the message "[alerting-exception] routing is required for ...." .
***@***.***



Step 7: create the alert monitor. ***@***.***






The alerts are getting generated. But it is suppose to trigger the message channel to send message to SNS which is not happening. Not able to see logs or any exception message.

***@***.***


***@***.***


Main Problem:  Alerting / Montiors / "Alertname"/ update monitor page "Send Test Message" in Trigger/ Action is not working.

***@***.***


Please let me know if you need more information.


Thanks & Regards,
S.Lakshminarasimhan
Phone:+91-9884177007

**Comment by Hailong-am** [comment]
@vslekshminarasimhan have you follow the documentation to make sure all permission are setup? https://opensearch.org/docs/latest/observing-your-data/notifications/index/#amazon-sns-as-a-channel-type

Also, you can click on `See full error` button to see detailed error or open dev tools of chrome browser and inspect the network response

**Comment by praveensameneni** [comment]
Please update and re-open if you are still experiencing the issue
