### ISSUE TITLE
[BUG] Notifications Channels does not appear in Monitor Trigger Actions

### ISSUE THREAD

**Issue by josiasnonato** [opensearch-project/dashboards-notifications#218]
**Describe the bug**

When I create an actions in a Monitor Trigger, the only option is "Manage Channels" with a message: "There are no existing channels. Add a channel to create an action".

I've created a channel, but I can't it in the Trigger Actions.

**To Reproduce**
1. Go to 'Notifications' page
2. Click on 'Create channel'
3. Select the type: Slack and create click on button Create
PS.: My type is a Slack Channel.
4. Go to Alerting page
5. Click on Monitors Ribbon and create a Monitor
6. Choose the following items:
6.1. Per query monitor
6.2. Visual Editor
6.3. By internal - 1 minute
6.4. Index Pattern: {{ Put your index }}
6.5. Time field: timestamp
6.6. Triggers: Add another Trigger
6.7. Put a trigger name
6.8 Actions: Here is the problem

**Expected behavior**
I believe that I should select my channel or select some options to channels

**OpenSearch Version**
Opensearch 2.14.0

**Dashboards Version**
Opensearch Dashboards 2.14.0

**Plugins**
Alerting

**Screenshots**
1. The screen of my Notification channels
![notifications-screen](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/31247591/2806b448-81d4-4c7e-95d0-49613429cfbd)

2. The screen of my monitor showing the actions page
![alerting-monitor-triggers-actions-screen](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/31247591/2abd2169-66ca-4308-a2a9-d3f073e57f47)

**Host/Environment (please complete the following information):**
 - OS: The Opensearch is running on GCP VMs Debian 12 and Opensearch Dashboards is running in Kubernetes using the image: opensearchproject/opensearch-dashboards:2.14.0
 - Browser and version: Microsoft Edge - Version 125.0.2535.92

**Additional context**
 - User: My user has **all_access** permision.

**Comment by dblock** [comment]
Thanks for opening this.

[Catch All Triage - Attendees [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/gkamat), [5](https://github.com/getsaurabh02)]

**Comment by Hailong-am** [comment]
It has been fixed in 2.15 https://github.com/opensearch-project/notifications/issues/922
