### ISSUE TITLE
[BUG] 2.8.0.0 tag missing LICENSE file

### ISSUE THREAD

**Issue by inglor** [opensearch-project/dashboards-notifications#59]
**What is the bug?**
As per title

**How can one reproduce the bug?**
1. checkout 2.8.0.0 tag
2. observe missing LICENSE file

**What is the expected behavior?**
Expect the license to be there.

**What is your host/environment?**
N/A

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
N/A

**Comment by Hailong-am** [comment]
add the missing license file into 2.x branch, close it.
