### ISSUE TITLE
[BUG] Sync latest cypress to functional test repo

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/dashboards-notifications#83]
**What is the bug?**

https://github.com/opensearch-project/opensearch-dashboards-functional-test/tree/main/cypress/integration/plugins/notifications-dashboards don't have latest cypress test code

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by SuZhou-Joe** [comment]
#https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/773
